apiVersion: cirrus.ibm.com/v1alpha1
kind: Application
metadata:
  name: gsa-dev-prod
spec:
  replicas: 1
  quota: q512mb
  envFrom:
    - secretRef:
        name:  gsa-dev-prod-sec
  livenessProbe:
    httpGet:
      path: /health/ping
    periodSeconds: 300
    timeoutSeconds: 300
  readinessProbe:
    httpGet:
      path: /health/ping
    periodSeconds: 300
    timeoutSeconds: 300